# Site Settings
title: /home/assault
description: >-
  VRと現実の狭間
baseurl: "/"
twitter_username: SzlyNe_
github_username: Assault1892
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
lang: ja-JP
permalink: /:title.html

# Theme Settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-avatar
  - jekyll-relative-links
#  - jemoji
