# =======================================
# Theme Setting
# =======================================

# Nav
nav:
  home: /
  about: /about/
  archives: /archives/
  tags: /tags/

# Posts OverView
posts_overview:
  show_all: false
  count: 10
  sort_updated: false

# Links to your social media.
social_links:
  # email:
  github: https://github.com/Assault1892
  # linkedin:
  twitter: https://twitter.com/SzlyNe_
  # instagram:
  # youtube:

# Site Create Time
since:

# Favicon
favicon: /favicon.ico
